### PR TITLE
Updated checkarg function

### PR DESCRIPTION
**Pull request by vaibhav721**

### CODE REVIEW

**Comment by ulshell** [comment]
@vaibhav721  Kindly re-fork the repository and do changes again to get rid of conflicts.

**Review by srivkrnt — CHANGES_REQUESTED** [review]
Please resolve the conflicts.

**Comment by vaibhav721** [comment]
On which pull request I have to make changes?

**Comment by ulshell** [comment]
https://github.com/OpenGenus/memes/pull/128#issuecomment-476738592 see comment

**Comment by srivkrnt** [comment]
@vaibhav721  as @ulshell suggested . Fork the repository again because as I see your branch is 73 commits behind OpenGenus/master. Re Forking would be a good idea to avoid unnecessary problems. Either way first update your branch with any way you wish and make the changes again for the checkarg() function and then I would be able to review the changes and move forward with the pull.

**Comment by ulshell** [comment]
Kindly see this pull request @srivkrnt this need to be corrected or else close it

**Pull request closed without merging**
